//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapX.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Lanes {
            get {
                return ((int)(this["Lanes"]));
            }
            set {
                this["Lanes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com0")]
        public string SerialPort {
            get {
                return ((string)(this["SerialPort"]));
            }
            set {
                this["SerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public long MinLapTime {
            get {
                return ((long)(this["MinLapTime"]));
            }
            set {
                this["MinLapTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RaceMode {
            get {
                return ((int)(this["RaceMode"]));
            }
            set {
                this["RaceMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public long PreRaceDelay {
            get {
                return ((long)(this["PreRaceDelay"]));
            }
            set {
                this["PreRaceDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Lane1ParPin {
            get {
                return ((int)(this["Lane1ParPin"]));
            }
            set {
                this["Lane1ParPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Lane2ParPin {
            get {
                return ((int)(this["Lane2ParPin"]));
            }
            set {
                this["Lane2ParPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Lane3ParPin {
            get {
                return ((int)(this["Lane3ParPin"]));
            }
            set {
                this["Lane3ParPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Lane4ParPin {
            get {
                return ((int)(this["Lane4ParPin"]));
            }
            set {
                this["Lane4ParPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Lane5ParPin {
            get {
                return ((int)(this["Lane5ParPin"]));
            }
            set {
                this["Lane5ParPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseFastestLapSound {
            get {
                return ((bool)(this["UseFastestLapSound"]));
            }
            set {
                this["UseFastestLapSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\fastestlap.wav")]
        public string FastestLapFileName {
            get {
                return ((string)(this["FastestLapFileName"]));
            }
            set {
                this["FastestLapFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseDetectedLapSound {
            get {
                return ((bool)(this["UseDetectedLapSound"]));
            }
            set {
                this["UseDetectedLapSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\lapdetected.wav")]
        public string DetectLapFileName {
            get {
                return ((string)(this["DetectLapFileName"]));
            }
            set {
                this["DetectLapFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseRedLightSound {
            get {
                return ((bool)(this["UseRedLightSound"]));
            }
            set {
                this["UseRedLightSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\redlight.wav")]
        public string RedLightFileName {
            get {
                return ((string)(this["RedLightFileName"]));
            }
            set {
                this["RedLightFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseStartRaceSound {
            get {
                return ((bool)(this["UseStartRaceSound"]));
            }
            set {
                this["UseStartRaceSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\startrace.wav")]
        public string StartRaceFileName {
            get {
                return ((string)(this["StartRaceFileName"]));
            }
            set {
                this["StartRaceFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseRaceFinishedSound {
            get {
                return ((bool)(this["UseRaceFinishedSound"]));
            }
            set {
                this["UseRaceFinishedSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\racefinished.wav")]
        public string RaceFinishedFileName {
            get {
                return ((string)(this["RaceFinishedFileName"]));
            }
            set {
                this["RaceFinishedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color Lane1Color {
            get {
                return ((global::System.Windows.Media.Color)(this["Lane1Color"]));
            }
            set {
                this["Lane1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFA500")]
        public global::System.Windows.Media.Color Lane2Color {
            get {
                return ((global::System.Windows.Media.Color)(this["Lane2Color"]));
            }
            set {
                this["Lane2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF00")]
        public global::System.Windows.Media.Color Lane3Color {
            get {
                return ((global::System.Windows.Media.Color)(this["Lane3Color"]));
            }
            set {
                this["Lane3Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008000")]
        public global::System.Windows.Media.Color Lane4Color {
            get {
                return ((global::System.Windows.Media.Color)(this["Lane4Color"]));
            }
            set {
                this["Lane4Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0000FF")]
        public global::System.Windows.Media.Color Lane5Color {
            get {
                return ((global::System.Windows.Media.Color)(this["Lane5Color"]));
            }
            set {
                this["Lane5Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEE82EE")]
        public global::System.Windows.Media.Color Lane6Color {
            get {
                return ((global::System.Windows.Media.Color)(this["Lane6Color"]));
            }
            set {
                this["Lane6Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ParallelPortInvertLogic {
            get {
                return ((bool)(this["ParallelPortInvertLogic"]));
            }
            set {
                this["ParallelPortInvertLogic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpStartAction {
            get {
                return ((int)(this["JumpStartAction"]));
            }
            set {
                this["JumpStartAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PersonalBestFileName {
            get {
                return ((string)(this["PersonalBestFileName"]));
            }
            set {
                this["PersonalBestFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsePersonalBestSound {
            get {
                return ((bool)(this["UsePersonalBestSound"]));
            }
            set {
                this["UsePersonalBestSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LaneStyle {
            get {
                return ((int)(this["LaneStyle"]));
            }
            set {
                this["LaneStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SamplingInterval {
            get {
                return ((int)(this["SamplingInterval"]));
            }
            set {
                this["SamplingInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowStats {
            get {
                return ((bool)(this["ShowStats"]));
            }
            set {
                this["ShowStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SensorType {
            get {
                return ((int)(this["SensorType"]));
            }
            set {
                this["SensorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Lane1SerPin {
            get {
                return ((int)(this["Lane1SerPin"]));
            }
            set {
                this["Lane1SerPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Lane2SerPin {
            get {
                return ((int)(this["Lane2SerPin"]));
            }
            set {
                this["Lane2SerPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Lane3SerPin {
            get {
                return ((int)(this["Lane3SerPin"]));
            }
            set {
                this["Lane3SerPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Lane4SerPin {
            get {
                return ((int)(this["Lane4SerPin"]));
            }
            set {
                this["Lane4SerPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SerialPortInvertLogic {
            get {
                return ((bool)(this["SerialPortInvertLogic"]));
            }
            set {
                this["SerialPortInvertLogic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1016")]
        public int SerialIOPort {
            get {
                return ((int)(this["SerialIOPort"]));
            }
            set {
                this["SerialIOPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("888")]
        public int ParallelIOPort {
            get {
                return ((int)(this["ParallelIOPort"]));
            }
            set {
                this["ParallelIOPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RMSUseInpOut32 {
            get {
                return ((bool)(this["RMSUseInpOut32"]));
            }
            set {
                this["RMSUseInpOut32"] = value;
            }
        }
    }
}
